# Starter pipeline


trigger:
  - main

pool:
    default

steps:
  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'aws kubernetes'
      manifests: 'nginx-deployment.yaml'
